apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
        - name: vite-app
          image: arnab-sahoo/vite-app:latest  
          ports:
            - containerPort: 3000           
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysealedsecret
                  key: DBUSERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysealedsecret
                  key: DBPASSWORD